services:
  - type: web
    name: email-guard-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python start_backend.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: JWT_SECRET_KEY
        generateValue: true 